kafka:
  brokers:
    - "broker1:9092"
    - "broker2:9092"
  consumers:
    - topic: "input_topic_1"
      group: "group1"
      path: "/path/to/save/files1"
    - topic: "input_topic_2"
      group: "group2"
      path: "/path/to/save/files2"
  producers:
    - topic: "output_topic_1"
      path: "/path/to/read/files1"
    - topic: "output_topic_2"
      path: "/path/to/read/files2"

logging:
  file_path: "./kafka-client.log"

tls:
  enabled: true
  ca_file: "/path/to/ca.pem"
  cert_file: "/path/to/cert.pem"
  key_file: "/path/to/key.pem"
  passphrase: "your-passphrase"
