kafka:
  brokers:
    - "broker1:9093"
    - "broker2:9093"
  consumer:
    group_id: "test_group"
    topics:
      - "TEST"
  producer:
    topic: "TEST"
tls:
  enabled: true
  client_cert_file: "client-cert.pem"
  client_key_file: "client-key.pem"
  ca_cert_file: "ca-cert.pem"
